### ISSUE TITLE
Upgraded to the new Unreal Engine and now not recognizing the pyinit

### ISSUE THREAD

**Issue by geevargs** [orig74/DroneSimLab#21]
![image](https://user-images.githubusercontent.com/29235421/31202007-ac97fc58-a915-11e7-9111-d00bcbecb41d.png)

**Comment by geevargs** [comment]
I use the selected viewport when I press play
/DroneLab/MyProject2$./build.sh 
Using clang version '3.8.0' (string), 3 (major), 8 (minor), 0 (patch)
@progress push 5%
@progress 'Generating code...' 0%
@progress 'Generating code...' 67%
@progress 'Generating code...' 100%
@progress pop
Using bundled libc++ standard C++ library.
/bin/sh  -c '/bin/sh "/local/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/FixDependencies.sh" && echo "Dummy" >> "/local/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UE4Editor.link"'
Target is up to date

**Comment by geevargs** [comment]
This is the error I am getting:
2017.10.04-22.10.11:129][142]LogTemp:Warning: called APyServerTickActor::BeginPlay

loading libfile /DroneLab/MyProject2/Binaries/Linux/libUE4Editor-MyProject2.so
start loading lib file
done loading lib file
pyinit imported
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/DroneLab/UE4PyhtonBridge/src/Wrappers/pyinit.py", line 6, in <module>
    from Wrappers import phandlers
  File "/DroneLab/UE4PyhtonBridge/src/Wrappers/phandlers.py", line 4, in <module>
    import cv2
ImportError: /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0: undefined symbol: cairo_ft_font_options_substitute
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pyinit' is not defined
[2017.10.04-22.10.11:189][142]PIE: Info Play in editor start time for /Game/Maps/UEDPIE_0_SMALL -60.810588
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pyinit' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pyinit' is not defined
Traceback (most recent call last):

**Comment by orig74** [comment]
It seems that it has some issues with the OpenCV installation.
first to try to install the libpangocairo manually in the unreal docker image by running:
`sudo apt-get install libpangocairo-1.0-0`
If that doesn't help, try to rebuild the image with the nocache flag e.g. 
`cd dockers/unreal_engine_4 && ../build --nocache`

**Comment by orig74** [comment]
Please also try installing
`sudo apt-get install libpango1.0-dev`
in the same way before recompiling the image

**Comment by geevargs** [comment]
![image](https://user-images.githubusercontent.com/29235421/31251573-36af991a-a9d3-11e7-9848-e41eab1070c3.png)

**Comment by geevargs** [comment]
It says project file not found and I can change /DroneLab/MyProject2 but I still get the pyinit not found

**Comment by geevargs** [comment]
![image](https://user-images.githubusercontent.com/29235421/31252062-d5152ff6-a9d4-11e7-8c9a-7c00ff6c6723.png)

**Comment by geevargs** [comment]
if i modify the path to the path in the docker and it runs but gives this error and I have already installed  sudo apt-get install libpangocairo-1.0-0 &  sudo apt-get install libpango1.0-dev and recompiled the image but still get the same error

**Comment by orig74** [comment]
you need to change the path in the script set_ue4_bridge.sh
and run it again e.g.
`./set_ue4_bridge.sh`

**Comment by orig74** [comment]
also, I think I misled you :(
when you start the unreal docker image you need to give it the project file path on the host machine
e.g.

`PROJECT_FILES_DIR=<your host project file dir (absolute path)> ./run_image.sh
`

**Comment by geevargs** [comment]
I am gonna try reinstalling it again with the PROJECT_FILES_DIR=<your host project file dir (absolute path)> ./run_image.sh

**Comment by orig74** [comment]
You don't need to reinstall it again. just stop the image and run it again:
`./stop.sh`
`PROJECT_FILES_DIR=<your host project file dir (absolute path)> ./run_image.sh`

**Comment by geevargs** [comment]
I just wanna know the Project Dir is from the Host or the docker...it works with the docker

DroneLab$cd MyProject2/
/DroneLab/MyProject2$./build.sh       
ERROR: System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/sujith/DroneSimLab/MyProject2/MyProject2.uproject".
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0x7f01f5d5d2c0 + 0x001f4> in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, System.String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) <0x7f01f5d5d210 + 0x0004d> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost) <0x7f01f5bcc530 + 0x000e4> in <filename unknown>:0 
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize) <0x7f01f5bcc4f0 + 0x00030> in <filename unknown>:0 
  at System.IO.StreamReader..ctor (System.String path, Boolean detectEncodingFromByteOrderMarks) <0x7f01f5bcc420 + 0x0003b> in <filename unknown>:0 
  at System.IO.StreamReader..ctor (System.String path) <0x7f01f5bcc400 + 0x00016> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader:.ctor (string)
  at System.IO.File.ReadAllText (System.String path) <0x7f01f5d5b650 + 0x00033> in <filename unknown>:0 
  at UnrealBuildTool.JsonObject.Read (System.String FileName) <0x41c80480 + 0x00014> in <filename unknown>:0 
  at UnrealBuildTool.ProjectDescriptor.FromFile (System.String FileName) <0x41c7f9e0 + 0x00047> in <filename unknown>:0 
  at UnrealBuildTool.RulesCompiler.CreateProjectRulesAssembly (UnrealBuildTool.FileReference ProjectFileName) <0x41c7f4c0 + 0x0005f> in <filename unknown>:0 
  at UnrealBuildTool.UEBuildTarget.CreateTarget (UnrealBuildTool.TargetDescriptor Desc, System.String[] Arguments, Boolean bCompilingSingleFile) <0x41c7e730 + 0x000ab> in <filename unknown>:0 
  at UnrealBuildTool.UnrealBuildTool.RunUBT (UnrealBuildTool.BuildConfiguration BuildConfiguration, System.String[] Arguments, UnrealBuildTool.FileReference ProjectFile) <0x41c77000 + 0x01963> in <filename unknown>:0

**Comment by orig74** [comment]
The path needs to be from the docker machine. Since the unreal engine is running under docker, it is not aware of the host file system

**Comment by geevargs** [comment]
![image](https://user-images.githubusercontent.com/29235421/31292310-ca3e2aca-aa87-11e7-9dbd-6cb20366fdf5.png)

**Comment by geevargs** [comment]
upgraded unreal from 4.14 to 4.17.2 
now it deosnt get data from sitl

**Comment by geevargs** [comment]
![image](https://user-images.githubusercontent.com/29235421/31301028-feab6d4e-aaab-11e7-8342-5050532703b0.png)

**Comment by geevargs** [comment]
I did a ping test from the SITL image to the host works fine...and I did a print after line 100 and before line 83

**Comment by geevargs** [comment]
/home/sujith/Downloads/Pasted image at 2017_10_06 01_49 PM.png

**Comment by geevargs** [comment]
![pasted image at 2017_10_06 01_49 pm](https://user-images.githubusercontent.com/29235421/31302225-e8e3c6e2-aab4-11e7-9b23-1182027590bc.png)

**Comment by geevargs** [comment]
It not reading the print in line 86

![image](https://user-images.githubusercontent.com/29235421/31302508-2374f586-aab7-11e7-8f8e-84cae6990a08.png)

**Comment by orig74** [comment]
You are right , it is a network issue. Did you change the --net=host flag to something else when you run the docker image?

**Comment by geevargs** [comment]
No I ran it as is

**Comment by geevargs** [comment]
I changed line RUN 22 :  useradd -o -u $UID docker and line 17 I added RUN apt-get -y install software-properties-common python-software-properties

**Comment by orig74** [comment]
Did you run the example properly?
you need to run in each tmux pane:
`python drone_main.py`
and the hit the play button in the editor
show me the tmux screen after you do that.

**Comment by geevargs** [comment]
![screenshot from 2017-10-06 19 02 14](https://user-images.githubusercontent.com/29235421/31303813-f898cc90-aac8-11e7-81a4-be1dcaa63976.png)

**Comment by orig74** [comment]
I am trying to understand if the drones are not moving only in the unreal engine or also in the SITL? do you see the position moves in the tmux windows?

**Comment by geevargs** [comment]
It doesn't move in either the SITL or unreal its like it doesn't reach either of them.

**Comment by orig74** [comment]
I am suspecting the IP addresses might have changed. Take a look at the config file:
demos/unreal_proxies/two_drones/config.py
make sure the IP addresses there are correct.
This can happen when you have a few docker images running and starting in an order I didn't expect. Make sure that the IP address of zmq_pub_unreal_proxy is indeed 172.17.0.1.

also, take a look at the "demos/unreal_proxies/two_drones/unreal_proxy.py" in line 28. this is how I calculate the IP address of the drone docker containers (we have two) and the unreal prints it to the screen make sure these addresses are the right addressed also.

I checked in my working version these are the IPs of the three containers:
drone 1  is 172.17.0.2
drone 2 is 172.17.0.3
the unreal editor is 172.17.0.1

you can use `ip addr show` to see the addresses

**Comment by geevargs** [comment]
1) config.py shows zmq_pub_drone_fdm=('172.17.0.2',5566) and zmq_pub_unreal_proxy=('172.17.0.1',5577) and in ifconfig docker0 is 172.17.0.1.
2) connecting to tcp://172.17.0.3:5566 and tcp://172.17.0.2:5566 in unreal engine docker

**Comment by orig74** [comment]
please show me the output of the `ip addr show` of the three containers.

**Comment by geevargs** [comment]
![image](https://user-images.githubusercontent.com/29235421/31354360-0335b464-aceb-11e7-9434-1952fbd6b88c.png)

**Comment by geevargs** [comment]
I am checking to see if its a firewall configuration and I did a iptables -F and that cleared it up....It works now

**Comment by orig74** [comment]
Good!
Let me know if you still have stability issues. The next step will be to try to run it a standalone game
